"""
3EMA + BX Trender Strategy Engine
Fully automated signal generation for S&P 500 stocks
"""

import numpy as np
import pandas as pd
from dataclasses import dataclass
from enum import Enum
from typing import Dict, List, Tuple, Optional


class SignalType(Enum):
    """Signal types generated by strategy"""
    LONG = "LONG"
    SHORT = "SHORT"
    NO_SIGNAL = "NO_SIGNAL"


class TrendType(Enum):
    """Trend classification"""
    UPTREND = "UPTREND"
    DOWNTREND = "DOWNTREND"
    CONSOLIDATION = "CONSOLIDATION"


@dataclass
class Signal:
    """Signal generated by strategy"""
    signal_type: SignalType
    timestamp: pd.Timestamp
    price: float
    ema_21: float
    ema_89: float
    ema_200: float
    bx_signal: str  # 'GREEN_DOT' or 'RED_DOT'
    bx_trend_line: float
    trend_type: TrendType
    confidence: float  # 0-100


@dataclass
class Trade:
    """Trade execution record"""
    entry_signal: Signal
    entry_price: float
    entry_time: pd.Timestamp
    position_type: SignalType  # LONG or SHORT
    stop_loss: float
    risk_amount: float
    position_size: int
    
    exit_signal: Optional[Signal] = None
    exit_price: Optional[float] = None
    exit_time: Optional[pd.Timestamp] = None
    exit_reason: Optional[str] = None  # "TP", "SL", "SIGNAL"
    
    @property
    def pnl(self) -> float:
        """Profit/Loss if exit is defined"""
        if self.exit_price is None:
            return 0.0
        
        if self.position_type == SignalType.LONG:
            return (self.exit_price - self.entry_price) * self.position_size
        else:
            return (self.entry_price - self.exit_price) * self.position_size
    
    @property
    def pnl_percent(self) -> float:
        """P&L percentage"""
        if self.exit_price is None or self.entry_price == 0:
            return 0.0
        
        if self.position_type == SignalType.LONG:
            return ((self.exit_price - self.entry_price) / self.entry_price) * 100
        else:
            return ((self.entry_price - self.exit_price) / self.entry_price) * 100


class EMAIndicator:
    """Exponential Moving Average calculations"""
    
    def __init__(self, period: int):
        self.period = period
        self.ema = None
        self.multiplier = 2 / (period + 1)
    
    def calculate(self, prices: np.ndarray) -> np.ndarray:
        """Calculate EMA for price series"""
        if len(prices) < self.period:
            return np.full(len(prices), np.nan)
        
        ema = np.full(len(prices), np.nan)
        ema[self.period - 1] = np.mean(prices[:self.period])
        
        for i in range(self.period, len(prices)):
            ema[i] = (prices[i] * self.multiplier) + (ema[i - 1] * (1 - self.multiplier))
        
        return ema
    
    @staticmethod
    def update(last_ema: float, new_price: float, multiplier: float) -> float:
        """Update EMA with new price (for streaming)"""
        return (new_price * multiplier) + (last_ema * (1 - multiplier))


class BXTrender:
    """
    BX Trender Signal Generator
    Generates LONG/SHORT signals based on trend confirmation
    """
    
    def __init__(self, lookback: int = 20):
        self.lookback = lookback
    
    def calculate_signals(self, df: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculate BX Trender signals
        
        Returns:
            signal_dots: array of 1 (GREEN_DOT), -1 (RED_DOT), 0 (NO_SIGNAL)
            trend_line: array of trend line values
        """
        
        # Simplified BX implementation - detects trend reversals
        # In real TradingView, this would be more complex
        
        high = df['high'].values
        low = df['low'].values
        close = df['close'].values
        
        n = len(close)
        signal_dots = np.zeros(n)
        trend_line = np.zeros(n)
        
        # Calculate trend line using simple regression
        for i in range(self.lookback, n):
            window = close[i - self.lookback:i]
            x = np.arange(len(window))
            
            # Linear regression slope
            slope = np.polyfit(x, window, 1)[0]
            trend_line[i] = slope
            
            # Detect peaks and troughs for signal generation
            if i >= 2:
                # GREEN_DOT: Price breaks above resistance
                if close[i] > max(high[i - 2:i]) and trend_line[i] > 0:
                    signal_dots[i] = 1
                
                # RED_DOT: Price breaks below support
                if close[i] < min(low[i - 2:i]) and trend_line[i] < 0:
                    signal_dots[i] = -1
        
        return signal_dots, trend_line
    
    @staticmethod
    def is_valid_long_signal(
        bx_signal: int,
        trend_line_value: float,
        trend_line_above_zero: bool
    ) -> bool:
        """Check if GREEN_DOT signal is valid"""
        return bx_signal == 1 and trend_line_value > 0 and trend_line_above_zero
    
    @staticmethod
    def is_valid_short_signal(
        bx_signal: int,
        trend_line_value: float,
        trend_line_below_zero: bool
    ) -> bool:
        """Check if RED_DOT signal is valid"""
        return bx_signal == -1 and trend_line_value < 0 and trend_line_below_zero


class StrategyEngine:
    """Main strategy engine - combines EMAs and BX Trender"""
    
    def __init__(
        self,
        ema_fast_period: int = 21,
        ema_mid_period: int = 89,
        ema_slow_period: int = 200,
        consolidation_threshold: float = 0.02,  # 2% gap
        bx_lookback: int = 20
    ):
        self.ema_fast = EMAIndicator(ema_fast_period)
        self.ema_mid = EMAIndicator(ema_mid_period)
        self.ema_slow = EMAIndicator(ema_slow_period)
        
        self.consolidation_threshold = consolidation_threshold
        self.bx_trender = BXTrender(lookback=bx_lookback)
        
        self.last_signal = None
        self.trades: List[Trade] = []
    
    def analyze_trend(
        self,
        ema_21: float,
        ema_89: float,
        ema_200: float,
        price: float
    ) -> TrendType:
        """
        Determine current trend type
        
        UPTREND: EMA_21 > EMA_89 > EMA_200
        DOWNTREND: EMA_21 < EMA_89 < EMA_200
        CONSOLIDATION: narrow gap between EMAs
        """
        
        if np.isnan(ema_21) or np.isnan(ema_89) or np.isnan(ema_200):
            return TrendType.CONSOLIDATION
        
        # Calculate gap between fast and slow EMA
        gap = abs(ema_21 - ema_200) / ema_200
        
        if gap < self.consolidation_threshold:
            return TrendType.CONSOLIDATION
        
        if ema_21 > ema_89 > ema_200:
            return TrendType.UPTREND
        elif ema_21 < ema_89 < ema_200:
            return TrendType.DOWNTREND
        else:
            return TrendType.CONSOLIDATION
    
    def generate_signal(
        self,
        df: pd.DataFrame,
        current_idx: int,
        account_equity: float = 10000,
        risk_per_trade: float = 0.015  # 1.5%
    ) -> Optional[Signal]:
        """
        Generate trading signal for current candle
        
        Args:
            df: DataFrame with OHLCV data
            current_idx: current candle index
            account_equity: current account balance
            risk_per_trade: risk percentage per trade
        
        Returns:
            Signal object if valid signal, None otherwise
        """
        
        # Calculate EMAs for entire series up to current index
        prices = df['close'].values[:current_idx + 1]
        ema_21_series = self.ema_fast.calculate(prices)
        ema_89_series = self.ema_mid.calculate(prices)
        ema_200_series = self.ema_slow.calculate(prices)
        
        ema_21 = ema_21_series[current_idx]
        ema_89 = ema_89_series[current_idx]
        ema_200 = ema_200_series[current_idx]
        
        # Analyze trend
        trend = self.analyze_trend(ema_21, ema_89, ema_200, df['close'].iloc[current_idx])
        
        # No trades in consolidation
        if trend == TrendType.CONSOLIDATION:
            return None
        
        # Calculate BX Trender signals
        bx_signals, trend_line = self.bx_trender.calculate_signals(df[:current_idx + 1])
        bx_signal_value = bx_signals[current_idx]
        bx_trend_line = trend_line[current_idx]
        
        current_price = df['close'].iloc[current_idx]
        
        # LONG SIGNAL
        if trend == TrendType.UPTREND:
            # Check all conditions
            price_above_ema21 = current_price > ema_21
            bx_valid = BXTrender.is_valid_long_signal(
                bx_signal_value,
                bx_trend_line,
                bx_trend_line > 0
            )
            
            if bx_valid and price_above_ema21:
                # Find swing low for SL
                recent_lows = df['low'].iloc[max(0, current_idx - 20):current_idx].min()
                stop_loss = recent_lows * 0.99  # 1% below recent low
                
                risk = current_price - stop_loss
                risk_amount = account_equity * risk_per_trade
                position_size = int(risk_amount / risk) if risk > 0 else 0
                
                return Signal(
                    signal_type=SignalType.LONG,
                    timestamp=df.index[current_idx],
                    price=current_price,
                    ema_21=ema_21,
                    ema_89=ema_89,
                    ema_200=ema_200,
                    bx_signal="GREEN_DOT",
                    bx_trend_line=bx_trend_line,
                    trend_type=trend,
                    confidence=95.0
                )
        
        # SHORT SIGNAL
        elif trend == TrendType.DOWNTREND:
            # Check all conditions
            price_below_ema21 = current_price < ema_21
            bx_valid = BXTrender.is_valid_short_signal(
                bx_signal_value,
                bx_trend_line,
                bx_trend_line < 0
            )
            
            if bx_valid and price_below_ema21:
                # Find swing high for SL
                recent_highs = df['high'].iloc[max(0, current_idx - 20):current_idx].max()
                stop_loss = recent_highs * 1.01  # 1% above recent high
                
                risk = stop_loss - current_price
                risk_amount = account_equity * risk_per_trade
                position_size = int(risk_amount / risk) if risk > 0 else 0
                
                return Signal(
                    signal_type=SignalType.SHORT,
                    timestamp=df.index[current_idx],
                    price=current_price,
                    ema_21=ema_21,
                    ema_89=ema_89,
                    ema_200=ema_200,
                    bx_signal="RED_DOT",
                    bx_trend_line=bx_trend_line,
                    trend_type=trend,
                    confidence=95.0
                )
        
        return None
    
    def check_exit_signal(
        self,
        trade: Trade,
        current_signal: Optional[Signal]
    ) -> Tuple[bool, Optional[str]]:
        """
        Check if we should exit current trade
        
        Returns:
            (should_exit, exit_reason)
        """
        
        if current_signal is None:
            return False, None
        
        # Exit if opposite signal appears and trade is profitable
        if trade.position_type == SignalType.LONG and current_signal.signal_type == SignalType.SHORT:
            return True, "OPPOSITE_SIGNAL"
        
        if trade.position_type == SignalType.SHORT and current_signal.signal_type == SignalType.LONG:
            return True, "OPPOSITE_SIGNAL"
        
        return False, None
